const productsData = [
    {
      name: "Apple",
      category: "Fruit",
      price: "30",
      quantity: "15",
      date: "2024-02-27",
    },
    {
      name: "Banana",
      category: "Fruit",
      price: "20",
      quantity: "20",
      date: "2024-02-26",
    },
    {
      name: "Orange",
      category: "Fruit",
      price: "25",
      quantity: "18",
      date: "2023-09-22",
    },
    {
      name: "Tomato",
      category: "Vegetable",
      price: "40",
      quantity: "12",
      date: "2023-12-25",
    },
    {
      name: "Potato",
      category: "Vegetable",
      price: "35",
      quantity: "25",
      date: "2024-01-30",
    },
    {
      name: "Carrot",
      category: "Vegetable",
      price: "30",
      quantity: "20",
      date: "2024-01-23",
    },
    {
      name: "Lettuce",
      category: "Vegetable",
      price: "15",
      quantity: "30",
      date: "2024-02-15",
    },
    {
      name: "Mango",
      category: "Fruit",
      price: "50",
      quantity: "10",
      date: "2024-03-03",
    },
    {
      name: "Watermelon",
      category: "Fruit",
      price: "40",
      quantity: "8",
      date: "2024-03-01",
    },
    {
      name: "Cucumber",
      category: "Vegetable",
      price: "25",
      quantity: "22",
      date: "2022-04-01",
    },
    // Add more rows as needed
    {
      name: "Grapes",
      category: "Fruit",
      price: "35",
      quantity: "16",
      date: "2024-02-29",
    },
    {
      name: "Pineapple",
      category: "Fruit",
      price: "45",
      quantity: "14",
      date: "2024-02-28",
    },
    {
      name: "Onion",
      category: "Vegetable",
      price: "30",
      quantity: "18",
      date: "2023-11-01",
    },
    {
      name: "Broccoli",
      category: "Vegetable",
      price: "55",
      quantity: "10",
      date: "2022-07-19",
    },
    {
      name: "Strawberry",
      category: "Fruit",
      price: "60",
      quantity: "12",
      date: "2021-10-10",
    },
    {
      name: "Bell Pepper",
      category: "Vegetable",
      price: "40",
      quantity: "20",
      date: "2023-03-02",
    },
    {
      name: "Spinach",
      category: "Vegetable",
      price: "20",
      quantity: "25",
      date: "2024-03-01",
    },
    {
      name: "Peach",
      category: "Fruit",
      price: "55",
      quantity: "14",
      date: "2022-09-04",
    },
    {
      name: "Cabbage",
      category: "Vegetable",
      price: "30",
      quantity: "18",
      date: "2023-12-28",
    },
    {
      name: "Cherry",
      category: "Fruit",
      price: "65",
      quantity: "10",
      date: "2022-03-01",
    }
  ];
  
  export default productsData;
  